; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

	TITLE	D:\강석민\주말ADVCPP\1일차\5_인라인함수.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?Add1@@YAHHH@Z					; Add1
PUBLIC	_main
; Function compile flags: /Odtp
; File d:\강석민\주말advcpp\1일차\5_인라인함수.cpp
_TEXT	SEGMENT
_n2$ = -8						; size = 4
_n1$ = -4						; size = 4
_main	PROC

; 12   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 13   : 	int n1 = Add1(1, 2);

	push	2
	push	1
	call	?Add1@@YAHHH@Z				; Add1
	add	esp, 8
	mov	DWORD PTR _n1$[ebp], eax

; 14   : 	int n2 = Add2(1, 2);

	mov	eax, 1
	add	eax, 2
	mov	DWORD PTR _n2$[ebp], eax

; 15   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File d:\강석민\주말advcpp\1일차\5_인라인함수.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?Add1@@YAHHH@Z PROC					; Add1

; 8    : 	   int Add1(int a, int b) { return a + b; }

	push	ebp
	mov	ebp, esp
	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]
	pop	ebp
	ret	0
?Add1@@YAHHH@Z ENDP					; Add1
_TEXT	ENDS
END
